"""remove topics column from documents metadata table

Revision ID: 803fba855fac
Revises: a519a5d2ab99
Create Date: 2026-03-03 03:45:33.189774

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '803fba855fac'
down_revision: Union[str, Sequence[str], None] = 'a519a5d2ab99'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('document_metadata', 'topics')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('document_metadata', sa.Column('topics', sa.TEXT(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
